include: package:flutter_lints/flutter.yaml

linter:
  # https://github.com/dart-lang/lints/blob/main/lib/core.yaml
  rules:
    avoid_function_literals_in_foreach_calls: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    always_declare_return_types: true
    avoid_print: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    collection_methods_unrelated_type: true
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
    depend_on_referenced_packages: true
    empty_catches: true
    file_names: true
    hash_and_equals: true
    implicit_call_tearoffs: true
    library_annotations: true
    no_duplicate_case_values: true
    no_wildcard_variable_uses: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    prefer_generic_function_type_aliases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    secure_pubspec_urls: true
    type_literal_in_constant_pattern: true
    unnecessary_overrides: true
    unrelated_type_equality_checks: true
    use_string_in_part_of_directives: true
    valid_regexps: true
    void_checks: true
    
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
