name: slt_assesment
description: "This is an assesment project for Synergy of Lake Technology"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # HTTP
  dio: 5.4.3+1

  # Data classes
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
  build_runner: 2.4.11
  freezed: 2.5.2
  json_serializable: 6.8.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/